### ISSUE TITLE
Having problems of integrating a real-world road map of OSM into the model 

### ISSUE THREAD

**Issue by shafiuyushawu** [AndreaVidali/Deep-QLearning-Agent-for-Traffic-Signal-Control#14]
I am an undergraduate student currently embarking  on my final year project. I have downloaded and run your code with no errors. I I had an idea of integrating the real road map of my country in Open Street Map (OSM) into the model, but has some challenges in doing it. Please can you help?

**Comment by AndreaVidali** [comment]
Hi @ibnsco , I personally haven't tried to import OSM maps into SUMO, so I can't be of much help. Anyway, I think that the two links below could have the necessary info in order to solve your problem.

[link 1](https://sumo.dlr.de/docs/Networks/Import/OpenStreetMap.html)
[link 2](https://sumo.dlr.de/docs/Tutorials/Import_from_OpenStreetMap.html)

**Comment by shafiuyushawu** [comment]
Thank you very much.
