### ISSUE TITLE
Does not use separate target network

### ISSUE THREAD

**Issue by ThisIsIsaac** [AndreaVidali/Deep-QLearning-Agent-for-Traffic-Signal-Control#4]
## Question

Is there a reason why you did not implement a separate target network? Unless you have tried it and made a decision to not use separate target network, it is one of the two biggest improvements that the DQN paper suggested. I didn't see any explanation from your paper either. Would love to hear what you think. Thanks

## Why separate network is important

Below is from the DQN paper published in Nature
<img width="878" alt="Screen Shot 2019-06-26 at 21 09 11 PM" src="https://user-images.githubusercontent.com/49523965/60178548-bef75380-9856-11e9-9bbe-a5331e7de0a0.png">

And the table it refers to:
<img width="1803" alt="Screen Shot 2019-06-26 at 21 10 26 PM" src="https://user-images.githubusercontent.com/49523965/60178576-d7676e00-9856-11e9-8276-7c7180628b9b.png">

**Comment by ThisIsIsaac** [comment]
I have implemented a separate target network. Compared to 100 epochs on both the original & separate target network version, the latter display 30% increase in performance.

**Comment by AndreaVidali** [comment]
I have implemented a target network in my private work, following my thesis. Yes, I know that a TN gives a boost to performance, but the intent of this repo is to give a starting point to people that want to work on this topic. Therefore I tried to simplify as much as possible the overall work (which it still achieves good performance even without TN), and let others experiments and expand the work as they like.

**Comment by ThisIsIsaac** [comment]
You should rename the repo or explicitly mention that it is not a complete implementation of DQN. It is very misleading because no where in the code, readme, or your thesis is there any mention of your intent to only partially implement DQN.

**Comment by AndreaVidali** [comment]
As you stated, this is not an implementation of the DQN system proposed in the DQN paper. Here I have implemented my own very simple version of a deep q-learning system, which is not directly inspired by DQN, and that is why you can't see any mention of DQN. In this work, I have included only the parts that I found a good trade-off between performance and understandability. For example, I also would like to point out that DQN also uses a Convolutional NN, but in this work, a Feedforward NN is used. 

You are free and encouraged to implement a vanilla DQN system applied to Traffic Control, but this is not what this repo is about. This repo is just to give a practical starting point to anyone that wants to dive in this topic using SUMO, also because when I started working on it I found out that there weren't any good resources online.

**Comment by way-thu** [comment]
@ThisIsIsaac sorry to bother u, can u share the code which implemented a separate target network? I want to use it for a better learning.

**Comment by way-thu** [comment]
@ThisIsIsaac thanks a lot!
